### ISSUE TITLE
Mixing terms "block hash" and "header hash" is confusing/sub optimal

### ISSUE THREAD

**Issue by ordtrogen** [Chia-Network/chia-blockchain-gui#120]
In the list of blocks, the first column is named "Header Hash"

![image](https://user-images.githubusercontent.com/15184875/109941219-37244680-7cd3-11eb-9fc3-c0fde9fb10de.png)

And the search field header uses "header hash", but the input field seems to ask for a "Block hash"

![image](https://user-images.githubusercontent.com/15184875/109941780-ca5d7c00-7cd3-11eb-8ee3-af6e97c75a1b.png)

I think only one term should be used (and would prefer "Block hash" as it's simpler and easier to translate)

I'm guessing that in a technical sense, there is a difference between the hash of an entire block and a hash of its header. But let's keep it simple and just use "Block hash" and maybe have one of them tooltip question mark things with a popup that explains more.

**Comment by hoffmang9** [comment]
On this one you are correct it's an issue, but "block hash" isn't a good solution either. Let me think about.

Here is `chia show -h` for reference:
```
  -bh, --block-header-hash-by-height TEXT
                                  Look up a block header hash by block height
  -b, --block-by-header-hash TEXT
                                  Look up a block by block header hash
```

**Comment by mariano54** [comment]
I would change it to header hash. The whole codebase uses header hash

**Comment by ordtrogen** [comment]
Maybe be careful how much of the inner machinery to expose to the user, although looking up blocks by hash may not be the first thing the average user tries out :-)

**Comment by hoffmang9** [comment]
One of the unique things about chia is that the header hash is the consensus critical item. The transactions are just signed onto in the header hash by the farmer unlike say a BTC transaction where you have to refer to the hash of the whole block as the transactions are a fundamental part of the block from the consensus' point of view. I explain this because it's not just "everywhere in the code" but actually an important item. That said "header hash" may not yet be the best way to explain this to folks. Closing this though as it's, for now, header hash everywhere in RC5
