### ISSUE TITLE
[Bug] new harvester tab - raw and effective farm size has different values without any compressed plots

### ISSUE THREAD

**Issue by esaung** [Chia-Network/chia-blockchain-gui#1817]
### What happened?

I have 4,536 uncompressed k25 plots on testnet. The total farm size raw shows 2.769 TiB, and the effective farm size shows 2.753 TiBe. Because all of my plots are uncompressed, I would expect that the raw and effective farm size to be exactly the same.

![Screenshot 2023-06-01 at 3 35 55 PM](https://github.com/Chia-Network/chia-blockchain-gui/assets/93196638/eed3845f-5f8b-4a67-a88c-726018b341e6).

this is on mac/intel

### Version

2.0.0b3-dev120

### What platform are you using?

macOS

### What ui mode are you using?

GUI

**Comment by ChiaMineJP** [comment]
Raw plot file size and effective plot size usually is not exactly the same.
Effective plot size is calculated like this.
```
effective_plot_size = uint64(((2 * k) + 1) * (2 ** (k - 1))) * 0.78
```
In case `k=25`, effective_plot_size for a plot is always `667,397,652` (~636.48MiBe)
You mentioned you have 4,536 k=25 plots.
In this case, total effective plot size is always `2.753TiBe`.
`2.753TiBe = 667,397,652 * 4,536 / 1024 / 1024 / 1024 / 1024`

So effective plot size is always the same with `k` value while actual plot size differs even if `k` is the same.
Uncompressed plot size and effective plot size won't match because of the above.
