### ISSUE TITLE
[Bug] Wallet auto-login not working when using an encrypted keyring

### ISSUE THREAD

**Issue by felixbrucker** [Chia-Network/chia-blockchain-gui#1860]
### What happened?

When configuring a wallet to auto-login while using an encrypted keyring the auto-login is not working. Instead after starting the chia client and entering the keyring passphrase the wallet selection screen is shown always.

### Version

1.8.1

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by felixbrucker** [comment]
Bug still exists

**Comment by paninaro** [comment]
@seeden can you take a look? I'm able to repro using these steps:

1. Set "Enable Auto Login" to on
2. Set or change the passphrase for your keyring -- make sure that the "Save passphrase" checkbox is unchecked
3. Quit Chia and let all services stop
4. Launch Chia

As mentioned in the report, after the keyring passphrase is provided, the SelectKey screen is displayed.

The core issue is that the GUI is starting the wallet (via `start_service`) before the keyring has been unlocked. If you launch chia services from the CLI, the daemon waits for the keyring to become unlocked before starting any services. So for example:

```(venv)  $ chia start farmer
Daemon not started yet
Starting daemon
(Unlock Keyring) Passphrase:
Unlocking daemon keyring
chia_harvester: started
chia_farmer: started
chia_full_node: started
chia_wallet: started```

Arguably the wallet service should wait for the keyring to be unlocked before starting, since the WalletNode can't be fully  instantiated without the wallet key, but that would likely be a significant change.

**Comment by seeden** [comment]
I verified everything in GUI, and here is the current state:
1. GUI is waiting until keyringStatus.isKeyringLocked === false
2. GUI will run services only when isKeyringLocked === false 

I also tried to wait 30 seconds after the keyring unlock but nothing changed.
My second thought was to invalidate loggedInFingerprint but it is always null.
I think that GUI is doing a correct job and there is no issue.

Maybe it is somehow related do the backend and it is doing something else because we are using only RPC.
@paninaro do you have any idea what can be wrong?

**Comment by seeden** [comment]
Fixed via https://github.com/Chia-Network/chia-blockchain-gui/pull/1982
