### ISSUE TITLE
[FR] UI improvements for common plotting questions

### ISSUE THREAD

**Issue by salamanders** [Chia-Network/chia-blockchain-gui#243]
Things that may help beginners (like me!) with the UI.  I kept a list of things that made me think "huh?" until I dug into docs or asked in Keybase/Reddit.

1.  Remove K25s from the list - if you need to make a K25, use the command line.
2. Put all K33+ under an advanced setting - we don't need to ever change that for 10 years.
3. "Plotting in parallel can save time" - append "as long as you have enough RAM, CPU, and fast enough disks."
4. (lowpriority) Default RAM max usage to the most efficient for that K.  (6900?). Or maybe 4608 is already the best bang-for-your-buck?
5. "Queue Name" is the most confusing thing, esp when you try to explain the diff between parallel and "add to queue" when you start talking about "want to have a delay".  Queue Name should be non-Advanced.
6. (lowpriority) Now that Bitfield is faster than before, remove from UI
7. (lowpriority) what does "exclude final directory" mean?
8. Say in the UI what "2nd temporary directory" does. maybe "Used for the second half of the plotting process, best when (some conditions)"
9. (lowpriority) Deleting a plot works for the plot, but when I'm deleting plots being created, I think I'd rather delete at the Queue level.  Or only get a warning when I'm deleting a plot that has started.
10. Default destination directory to last-used.

In general: "Plot in Parallel" with a Delay is a lot like "Add Plot to Queue" and I think it causes confusion.  To me, it is is a queue, but each plot starts early.  What I'd like is "Add Plot to Queue" and "Start Early - right after phase1 of the previous plot finishes"

** These are only my opinions and may not align with other noobs' confusion.

**Comment by hoffmang9** [comment]
A quibble is that new users shouldn't be going into advanced options and asking what this does. Danger - High Voltage - Lemme touch it!

Quite a few of these things are already on our roadmap but you triggered an idea. We should put all but k32 in an Advanced Option. There are a lot of uses for k25 that you're not aware of though farming to win XCH is not one of them.

We'd love to remove bitfield but it doesn't support pre-Nahalem processors. Not so much a problem in the G20 countries but farmers are especially not just from the G20.

RAM is an optimal mix that will change in 1.0.4.

Queue name is in advanced precisely because it's hard to use and we'd like something better. It was quick and dirty to launch a blockchain. Blockchain core code can not be changed in the future. The UI is a baby that's going to keep growing over time.

Welcome to week 4 of production.

**Comment by salamanders** [comment]
> new users shouldn't be going into advanced options and asking what this does

Yup yup totally agree.  Which is why (IMHO) just a little bit of the advanced stuff around parallel or queue-based could be moved up a level, then I'd never have to expand those areas.

**Comment by hoffmang9** [comment]
And there is the tradeoff. We were begged by people using the command line to add "Exclude Final Directory." No free lunches here.

**Comment by N418** [comment]
> Things that may help beginners (like me!) with the UI. I kept a list of things that made me think "huh?" until I dug into docs or asked in Keybase/Reddit.
> 
> 1. Remove K25s from the list - if you need to make a K25, use the command line.
> 2. Put all K33+ under an advanced setting - we don't need to ever change that for 10 years.

I disagree on your #1 and #2, I use them all the time, everyday.

**Comment by N418** [comment]
In fact, give me option for K36/37 for Windows GUI, I'll have hardware to parallel plot K36/K37.

**Comment by salamanders** [comment]
@N418 Disagreeing is great, I'm only one data point!

From the website - congratulations on the K37!  It says there "is at least one known" - you should add yourself to that!
