### ISSUE TITLE
[Bug] Full Wallet Resync Yields Wrapped CAT Address as to Address in Transaction List

### ISSUE THREAD

**Issue by BrandtH22** [Chia-Network/chia-blockchain-gui#2442]
### What happened?

When performing a full resync of the wallet, the transaction list for CAT tokens that are sent is populated with the wrapped CAT address and not the original sending address.

The issue being that if users attempt to send tokens to that wrapped CAT address they will incidentally double wrap their CAT.

Prior to resyncing (note the recent sent to address ends in 25g2):
![image](https://github.com/user-attachments/assets/0bf05622-7206-4555-9dda-881cd2df3927)

After resyncing (via deleting the wallet db, note the recent sent to address now ends in ezsx):
![image](https://github.com/user-attachments/assets/495be223-4738-497f-b3fb-157abfebf91e)

### Version

2.4.2

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by markelrod** [comment]
For now we are going to remove the display of the To: address to eliminate the possibility of double wrapping.

**Comment by ChiaMineJP** [comment]
Umm. So far I couldn't reproduce this problem.
Even if I deleted wallet db file to force re-sync, to address still shows the original address.

@BrandtH22 How could you know that the address `xch1...ezsx` was the wrapped (outermost) CAT address?
`Prior to resyncing` section there is already `xch1...ezsx` and it is likely the standard address.
I assume that you sent the CAT to your own addresses generated with a different derivation index because you received 0.7 just after you sent 0.7 to `xch1...ezsx`.

**Comment by markelrod** [comment]
PR 2446 addresses this by not showing or allowing user to copy full address
