### ISSUE TITLE
[Improvement][GUI][WIN10] Plotter only for GUI 

### ISSUE THREAD

**Issue by Handri-Kosada** [Chia-Network/chia-blockchain-gui#257]
It will be great if GUI has the button to enable / disable full node service, wallet service, farm service, and harvest service.

So we can use the GUI purely just for plotting.

**Comment by Muffexx** [comment]
This feature is highly anticipated!

I've searched several threads on Reddit and other forums and people are requesting this feature since even with disabled UPnP there are still plenty connections to other full nodes and the node stays synced.

Is there any workaround to only farm (on secondary/tertiary/etc. node)   when using the GUI?

regards

**Comment by Muffexx** [comment]
*Push*
