### ISSUE TITLE
Running 'npm run electron &' errors out...

### ISSUE THREAD

**Issue by NipBoss** [Chia-Network/chia-blockchain-gui#353]
Hello guys!
me again :)

I am on the final steps here of setting up a full node + farmer + harvester + wallet on CentOS 8 (cloudlinux distro).

and I get this error when running the command:

> chia-blockchain@ electron /chia-blockchain/chia-blockchain-gui
> electron .

/chia-blockchain/chia-blockchain-gui/node_modules/electron/dist/electron: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! chia-blockchain@ electron: `electron .`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the chia-blockchain@ electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubit/.npm/_logs/2021-05-04T23_46_32_648Z-debug.log

tried both, root and the admin user, same thing.
attached is the log file.
[2021-05-04T23_46_32_648Z-debug.log](https://github.com/Chia-Network/chia-blockchain-gui/files/6424458/2021-05-04T23_46_32_648Z-debug.log)

**Comment by waspper** [comment]
I faced similar error. It's basically due to missing dependencies. I tried to start GUI in an Ubuntu VM, and it was needed to install following packages:

<pre>
libnss3
libatk1.0-0
libatk-bridge2.0-0
libgdk-pixbuf2.0-0
libgtk-3-0 
libgbm-dev
</pre>

I think it's matter of looking for equivalent package names for your distro.

At the end, it was not possible to launch GUI. Got this issue:

<pre>
[1] 7356
chia@04c0cd323539:/chia-blockchain/chia-blockchain-gui$ 
> chia-blockchain@ electron /chia-blockchain/chia-blockchain-gui
> electron .

Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
/chia-blockchain/chia-blockchain-gui/node_modules/electron/dist/electron exited with signal SIGTRAP
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chia-blockchain@ electron: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chia-blockchain@ electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chia/.npm/_logs/2021-05-07T03_08_23_174Z-debug.log

[1]+  Exit 1                  npm run electron

</pre>

**Comment by NipBoss** [comment]
If you could try and set up VNC and let us know that would be amazing.

**Comment by justinreed270** [comment]
![Screenshot from 2021-05-13 21-11-38](https://user-images.githubusercontent.com/72054890/118206142-d7af8900-b42f-11eb-9618-3b48648343a1.png

I am having a similar issue where I have installed everything. The application launches only once after install. 
I have reinstalled Ubuntu 20.04 at least 5 times, maybe 8. Each reinstall the Chia GUI launches, runs for about 12 hours, then the application stops. It does not freeze, the CPU stops processing the plots. When I kill the program and try to relaunch I get the following error messages. Thoughts?
