### ISSUE TITLE
Harvester machines keep disconnecting from main, don´t connect back

### ISSUE THREAD

**Issue by cryptoshaman007** [Chia-Network/chia-blockchain-gui#378]
I have 3 computers, set one to be the main Node, and the other two as harversters.
Started all working ok, I could see the chalenges with diferent plot numbers on main node.
But after some time like hours or a day, harvesters chalenges stop showing on main.

Use windows GUI. 
I´m plotting on the two harvesters so restarting application everytime it is not working is not good.

Think I will stop using harvesters for the time... let it all conect individually.
Harvesters setup is hard and is not working properly.

**Comment by zoenberger** [comment]
Yeah I am having the exact same problem. I've followed the [Farming on many machines](https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines) directions a few times to be 100% sure I'm doing it right. 

I'm starting harvesting with `chia start harvester -r` and within a short period I can see challenges being done against plots on main node and harvester. 

Then after some amount of time (for me this has been typically in the 5-10 hour range), the connection is lost. I can tell because last attempted proofs are only done against the plots on main node. Then I run the start harvester command again and it's fine for a while again.

**Comment by cryptoshaman007** [comment]
Really anoying. the chia start harvester -r command for me don´t work.
Restarting the internet router sometimes fix but, its really random sometimes.
Stops workings for some hours, than come back, sometimes restarting aplication resolves, sometimes reseting router resolves, and sometines nothing resolves really. anoiyng

**Comment by BigSilverOrb** [comment]
I'm having the same problem with Ubuntu. Go to sleep each night with 10 harvesters running and showing on my farmer GUI, and by the next day at least half have disconnected. Impossibly frustrating.

**Comment by cryptoshaman007** [comment]
If I close the GUI, and just start a harvester with CLI
chia start harvester -r
it works way better and don´t disconects

**Comment by danzar** [comment]
Still happening to me on 1.2.11

**Comment by InvaderDolan** [comment]
Still getting similar problem:
`harvester harvester               : INFO     Reconnecting to peer {'host': '192.168.1.10', 'port': 8447}`
