### ISSUE TITLE
[BUG] GUI Total Chia farmed is locked at 50 TXCH, when wallet total balance is higher

### ISSUE THREAD

**Issue by mrxzius** [Chia-Network/chia-blockchain-gui#69]
on the Farming Overview the TXCH Block rewards is locked at 50 , when on the Wallet tab, the total Balance is higher. Seems that the TXCH locks out on 50 ( happened in three different GUI clients with 3 different private keys and different netowrks)

![image](https://user-images.githubusercontent.com/79389443/108614825-ab5e1080-73dc-11eb-9201-317e7862d9da.png)

![image](https://user-images.githubusercontent.com/79389443/108614830-b153f180-73dc-11eb-9778-13ec0fc69801.png)

**Comment by dorkmo** [comment]
same happened to me on beta27

**Comment by seeden** [comment]
@mariano54 I think this issue is related to wallet transactions pagination. We are downloading only the first 50 transactions. @Yostra added pagination because the user can have thousands of transactions. We have two options for how to solve this issue.
1. on the UI side I will download all transactions.
2. on the server side you will compute statistics and send them to the UI

Let me know what do you think.

**Comment by seeden** [comment]
@mariano54, @Yostra   will you add support for these values on the backend side?

**Comment by mariano54** [comment]
@Yostra could you take this one?

**Comment by seeden** [comment]
Already merged
