### ISSUE TITLE
[Bug] Foreign/UTF8 characters are not displayed correctly

### ISSUE THREAD

**Issue by Ealrann** [Chia-Network/chia-blockchain-gui#930]
### What happened?

Hello, 

Some foreign characters in NFT attributes are not displayed properly in the wallet. For example : 
```
Photography
MusÃ©e du Louvre
```
On their side, Mintgarden and Spacescan show them properly  

https://mintgarden.io/nfts/nft180hvw9wun06uqke37xkuxs0nvrjm2tfw6vty3hu7ncg22pda8mfquye3tw
https://www.spacescan.io/xch/nft/nft180hvw9wun06uqke37xkuxs0nvrjm2tfw6vty3hu7ncg22pda8mfquye3tw

If you send me your xch address, I'll give you one :+1: 

![GiocondaBad](https://user-images.githubusercontent.com/723000/184725036-7807edb2-9a3b-497a-9afd-1d6a08711e81.png)

### Version

1.5.1.dev

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by paninaro** [comment]
Happy to help @Ealrann :) https://paninaro.xch.cx/ --> `xch17mp20xhhy7l6m20u37nw4ft338r2tt2yquenu4earcyzjwqh6kksc8dyjc`

**Comment by Ealrann** [comment]
Just sent it ! :D

**Comment by paninaro** [comment]
Thanks for uncovering this interesting edge case. Long story short, because the metadata URL response for these arweave URLs returns a 304 redirect status code, a long-standing Electron net.request bug omits the content-type header from the response object. So by default the charset is interpreted as iso-8859-1 (I believe).

I have a workaround fix that works. Longer-term, there will be some upcoming changes that should further change how we fetch metadata.

**Comment by Ealrann** [comment]
Thank you, I sent you another one!
Any chance the fix is included in 1.5.1?

**Comment by paninaro** [comment]
> Thank you, I sent you another one! Any chance the fix is included in 1.5.1?

Yeah, we'll get it in. Thanks for reporting it!
