### ISSUE TITLE
"Are you sure you want to quit" dialog not in Crowdin

### ISSUE THREAD

**Issue by ordtrogen** [Chia-Network/chia-blockchain-gui#96]
I can't find this for translation in crowdin

![Skärmavbild 2021-02-25 kl  09 41 20](https://user-images.githubusercontent.com/15184875/109126580-b652d100-774d-11eb-9133-21d6c6a68764.png)

**Comment by jespino** [comment]
This require a bit of work because is in the electron code, that is not aware of the locale at all, probably needs a message from the application giving the current locale on startup and on change, loading the translations, and labeling the translations inside the code. I'm taking a look, I hope to have something soon (it is going to lead to some degree of repetition, but I hope I can move it somewhere shared between the web app and the electron app.

**Comment by jespino** [comment]
Added a PR to allow translations in the electron app, not only the quit menu, also the top bar menu :)

**Comment by seeden** [comment]
@jespino  thank you
